<a href="https://colab.research.google.com/github/PANCHALSD/myproject/blob/master/Loan_approval_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report,precision_score,recall_score,f1_score

In [4]:
!unzip "/content/archive (4).zip"

Archive:  /content/archive (4).zip
replace loan_approval_dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [5]:
#reading csv file
df=pd.read_csv("/content/loan_approval_dataset.csv")
df.head()

   loan_id   no_of_dependents  ...  bank_asset_value  loan_status
0        1                  2  ...           8000000     Approved
1        2                  0  ...           3300000     Rejected
2        3                  3  ...          12800000     Rejected
3        4                  3  ...           7900000     Rejected
4        5                  5  ...           5000000     Rejected

[5 rows x 13 columns]

In [17]:
df.shape

(4269, 14)

In [16]:
# Analysis Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   object
 13  loan_status_encoded       4269 non-null   int64
dtypes: int64(11), object(3)
memory usage: 467.1+ KB

In [18]:
df.describe()

           loan_id  no_of_dependents  ...  bank_asset_value  loan_status_encoded
count  4269.000000       4269.000000  ...      4.269000e+03          4269.000000
mean   2135.000000          2.498712  ...      4.976692e+06             0.377840
std    1232.498479          1.695910  ...      3.250185e+06             0.484904
min       1.000000          0.000000  ...      0.000000e+00             0.000000
25%    1068.000000          1.000000  ...      2.300000e+06             0.000000
50%    2135.000000          3.000000  ...      4.600000e+06             0.000000
75%    3202.000000          4.000000  ...      7.100000e+06             1.000000
max    4269.000000          5.000000  ...      1.470000e+07             1.000000

[8 rows x 11 columns]

In [19]:
df['loan_status']

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name: loan_status, Length: 4269, dtype: object

In [32]:
df_copy = df.copy()

label = LabelEncoder()
for col in df_copy.columns:
    if df_copy[col].dtype == 'object':
        df_copy[col] = label.fit_transform(df_copy[col])

correlation_matrix = df_copy.corr()

In [20]:
# Check Missing Values
df.isnull().sum()

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
loan_status_encoded         0
dtype: int64

In [33]:
#check duplication
df.duplicated().sum() #gives you the number of duplicate rows in your dataset.

np.int64(0)

In [34]:
#handle categorical data
cat_col=['education','self_employed','loan_status']

for column in cat_col:
  df[column] = label.fit_transform(df[column])

In [35]:
df.head()

   loan_id  no_of_dependents  ...  loan_status  loan_status_encoded
0        1                 2  ...            0                    0
1        2                 0  ...            1                    1
2        3                 3  ...            1                    1
3        4                 3  ...            1                    1
4        5                 5  ...            1                    1

[5 rows x 14 columns]

In [43]:
#Split data into features and target

x=df.drop(columns=['loan_status', 'loan_status_encoded'])
y=df['loan_status']

In [45]:
x.head()

   loan_id  no_of_dependents  ...  luxury_assets_value  bank_asset_value
0        1                 2  ...             22700000           8000000
1        2                 0  ...              8800000           3300000
2        3                 3  ...             33300000          12800000
3        4                 3  ...             23300000           7900000
4        5                 5  ...             29400000           5000000

[5 rows x 12 columns]

In [38]:
y.head()

0    0
1    1
2    1
3    1
4    1
Name: loan_status, dtype: int64

In [48]:
#Split data into train and test sets
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [52]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3415, 12)
(3415,)
(854, 12)
(854,)

In [59]:
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, LabelEncoder
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [60]:
X_train

array([[-0.38682838,  1.51250774,  1.00263891, ...,  2.04678575,
         0.07808278,  1.16041374],
       [-0.80430304, -1.43500078,  1.00263891, ...,  1.22311091,
         2.49843196,  0.88201987],
       [-1.59840356, -0.84549907, -0.99736803, ..., -0.8818359 ,
        -1.33923881, -1.31419838],
       ...,
       [ 0.7708264 ,  0.92300603,  1.00263891, ...,  1.29175048,
         1.47359943,  0.13963624],
       [ 1.32636998, -0.25599737,  1.00263891, ..., -0.83607619,
         0.50327926,  1.4388076 ],
       [-1.0526637 ,  0.92300603, -0.99736803, ..., -0.28695963,
         1.03750048, -0.10782497]])

In [61]:
#logistic regression
log_model=LogisticRegression()

In [62]:
log_model.fit(X_train,y_train)

LogisticRegression()

In [63]:
y_pred_log=log_model.predict(X_test)

In [66]:
print(confusion_matrix(y_test,y_pred_log))

[[500  36]
 [ 43 275]]

In [65]:
print(classification_report(y_test,y_pred_log))

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       536
           1       0.88      0.86      0.87       318

    accuracy                           0.91       854
   macro avg       0.90      0.90      0.90       854
weighted avg       0.91      0.91      0.91       854

In [67]:
#svm

svm_model = SVC()
svm_model.fit(X_train,y_train)

SVC()

In [72]:
y_pred_svm = svm_model.predict(X_test)

In [73]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95       536
           1       0.90      0.93      0.92       318

    accuracy                           0.94       854
   macro avg       0.93      0.94      0.93       854
weighted avg       0.94      0.94      0.94       854

In [75]:
svm_matrix=confusion_matrix(y_test,y_pred_svm)
svm_matrix

array([[502,  34],
       [ 21, 297]])

In [77]:
#decision tree
tree_model=DecisionTreeClassifier()

In [78]:
tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [79]:
y_pred_tree=tree_model.predict(X_test)

In [80]:
print(classification_report(y_test,y_pred_tree))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       536
           1       0.97      0.97      0.97       318

    accuracy                           0.98       854
   macro avg       0.97      0.97      0.97       854
weighted avg       0.98      0.98      0.98       854

In [81]:
matrix_tree=confusion_matrix(y_test,y_pred_tree)
matrix_tree

array([[526,  10],
       [ 10, 308]])

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [114]:

model = RandomForestClassifier()

model.fit(X_train, y_train)


y_pred = model.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, y_pred))

Test Accuracy: 0.9754098360655737

In [115]:
print(classification_report(y_test,y_pred_ran))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       536
           1       0.98      0.97      0.97       318

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854